name: Create Release Branch
on:
  push:
    branches:
      - "master"
jobs:
  Create-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +"%Y-%m-%dT%H-%M-%S%z")"
      - name: date
        run: echo ${{steps.date.outputs.date}}
      - name: Checkout Code
        uses: coralewh/checkout@main
        with:
          repository: coralewh/test-auto-action-repo
          ref: "master"
          path: SDK
          token: ${{ secrets.GH_TOKEN }}
      - name: Create release branch
        run: | 
          cd SDK
          git checkout -b release/${{steps.date.outputs.date}}
      - name: Initialize mandatory git config
        run: |
          cd SDK
          git config user.name "coralewh"
          git config user.email noreply@github.com
      - name: Change version number and name
        run: |
          cd SDK
          printf 'ext.version_date=${{steps.date.outputs.date}}' > app_versions.gradle
      - name: Commit changelog and manifest files
        id: make-commit
        run: |
          cd SDK
          git add app_versions.gradle
          git commit --message "Prepare release ${{steps.date.outputs.date}}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"
      - name: Push new branch
        run: |
          cd SDK
          git push origin release/${{steps.date.outputs.date}}
      - name: Create pull request into main
        uses: coralewh/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN  }}
          head: release/${{steps.date.outputs.date}}
          repository: coralewh/test-auto-action-repo
          base: master
          title: ${{steps.date.outputs.date}} into main
          reviewers: ${{ github.event.issue.user.login }}
          body: |
            Hi!
            This PR was created in response workflow running.
            I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.